### ISSUE TITLE
Exporting to jpeg in full resolution gives 1MB-file

### ISSUE THREAD

**Issue by Hicetnunc** [ncruces/RethinkRAW#2]
Exporting the result to jpeg has few options to controll the output. Without ticking an option, a full resolution jpeg is produced but it has only 1MB. Shouldn't full resolution jpeg be full quality as well (i.e. e.g. 10-15MB)?

**Comment by ncruces** [comment]
Full resolution exported JPEGs come straight from the full size previews generated by Adobe DNG Converter.
These are 8-bit sRGB JPEGs, with no chroma-subsampling, and a custom quantization table.

Getting a bit technical, the quantization table maps to an estimated quality of **between 80 and 91%** (in terms of the IJG standard tables), and to quality 8 (High) in the 0-12 Adobe scale.

Since these come straight out of DNG Converter, there is nothing I can do to improve the quality, sorry.

---

Export for for "web/print" produces 4:2:2 chroma-subsampled 8-bit sRGB JPEGs. Quality tries to map the Adobe 0-12 scale to IJG (but the mapping is subject to change). Downsampling uses Lanczos 2 (also subject to change).

More importantly, these are resized and recompressed from the above. I'm taking decent (but not great!) JPEGs and recompressing them. Only use this if you're going to be downscaling significantly!

OTOH, there's scope for improvement here.
